CREATE TABLE `f_orders` (
	`order_id` INT(11) NOT NULL,
	`store_id` INT(11) NOT NULL,
	`channel_id` INT(11) NOT NULL,
	`payment_order_id` INT(11) NOT NULL,
	`delivery_order_id` INT(11) NOT NULL,
	`driver_id` INT(11) NULL DEFAULT NULL,
	`hub_id` INT(11) NOT NULL,
	`order_status` VARCHAR(10) NOT NULL COLLATE 'utf8_general_ci',
	`order_amount` DECIMAL(10,2) NULL DEFAULT NULL,
	`order_delivery_fee` DECIMAL(10,2) NULL DEFAULT NULL,
	`order_delivery_cost` DECIMAL(10,2) NULL DEFAULT NULL,
	`order_created_hour` INT(11) NULL DEFAULT NULL,
	`order_created_minute` INT(11) NULL DEFAULT NULL,
	`order_created_day` INT(11) NULL DEFAULT NULL,
	`order_created_month` INT(11) NULL DEFAULT NULL,
	`order_created_year` INT(11) NULL DEFAULT NULL,
	`order_moment_created` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_accepted` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_ready` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_collected` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_in_expedition` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_delivering` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_delivered` TIMESTAMP NULL DEFAULT NULL,
	`order_moment_finished` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`order_id`) USING BTREE,
	INDEX `store_id` (`store_id`) USING BTREE,
	INDEX `channel_id` (`channel_id`) USING BTREE,
	INDEX `payment_order_id` (`payment_order_id`) USING BTREE,
	INDEX `delivery_order_id` (`delivery_order_id`) USING BTREE,
	INDEX `driver_id` (`driver_id`) USING BTREE,
	INDEX `hub_id` (`hub_id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
